/**
 * Attendance: the rules the check-in screen enforces, and the shape of a card.
 *
 * Everything here is also enforced in supabase/schema.sql. That duplication is
 * deliberate and is not redundancy: the copy here exists to fail fast and say
 * something useful while the student is still standing in the room, and the
 * copy in SQL exists because the browser is not a place to enforce anything.
 * If the two ever disagree, the database is right.
 */

import { rpc } from "./supabase";

export { hasBackend, BackendError } from "./supabase";

/**
 * Six characters, read off a wall.
 *
 * The alphabet excludes the pairs a tired person confuses across a lecture
 * theatre: no O against 0, no I or L against 1, no S against 5. A code is
 * generated by an officer, never here, but the screen still has to know which
 * characters are legal so it can silently drop the rest as they are typed.
 */
export const CODE_LENGTH = 6;
export const CODE_ALPHABET = "ABCDEFGHJKMNPQRTUVWXYZ2346789";

/** Strip anything that cannot be part of a code, and uppercase the rest. */
export function normalizeCode(raw) {
  return (raw || "")
    .toUpperCase()
    .split("")
    .filter((ch) => CODE_ALPHABET.includes(ch))
    .join("")
    .slice(0, CODE_LENGTH);
}

/**
 * Anchored at both ends, matching the pitch form's NEU_EMAIL and the SQL's
 * is_member_email(). The suffix-only version this mirrors was already found
 * once to accept "someone@gmail.com.jordan@northeastern.edu".
 */
export const MEMBER_EMAIL =
  /^[^\s@]+@(northeastern\.edu|husky\.neu\.edu|neu\.edu)$/i;

/** Lowercase and trim, so one person is one card. Mirrors the SQL. */
export function normalizeEmail(raw) {
  return (raw || "").trim().toLowerCase();
}

/**
 * The message shown under a field, or "" when the value is fine.
 *
 * Wording is the student's next action, not a description of their mistake.
 */
export function validate({ code, name, email }) {
  const errors = {};
  if (normalizeCode(code).length < CODE_LENGTH) {
    errors.code = "Enter all six characters from the screen.";
  }
  if (!(name || "").trim()) {
    errors.name = "Please add your name.";
  }
  const clean = normalizeEmail(email);
  if (!clean) {
    errors.email = "Please add your email.";
  } else if (!MEMBER_EMAIL.test(clean)) {
    errors.email = "Use your Northeastern address.";
  }
  return errors;
}

/**
 * Why a check-in was refused, in the student's terms.
 *
 * Keyed by the `reason` strings check_in() returns. An unrecognised reason
 * falls back to something honest rather than to the raw key: a new failure mode
 * added to the SQL should degrade to a sentence, not to "email_domain".
 */
const REASONS = {
  code_invalid: "That code does not match. Check the screen at the front.",
  code_expired: "That code has expired. Ask an officer for the current one.",
  email_domain: "Use your Northeastern address.",
  name_required: "Please add your name.",
};

export function reasonMessage(reason) {
  return REASONS[reason] || "That did not go through. Try again in a moment.";
}

/**
 * Which field a refusal belongs to, so the message lands under the input that
 * caused it rather than in a general error area the eye has to hunt for.
 */
const REASON_FIELD = {
  code_invalid: "code",
  code_expired: "code",
  email_domain: "email",
  name_required: "name",
};

export function reasonField(reason) {
  return REASON_FIELD[reason] || null;
}

/** The session the room is in right now, or null between sessions. */
export async function currentSession(options) {
  return rpc("current_session", {}, options);
}

/**
 * Submit a check-in and get the card back in the same round trip.
 *
 * Returns the function's own envelope untouched: `{ ok: true, card, ... }` or
 * `{ ok: false, reason }`. Callers branch on `ok` rather than on exceptions,
 * because a wrong code is an expected outcome and not an error.
 */
export async function checkIn({ code, name, email }, options) {
  return rpc(
    "check_in",
    {
      p_code: normalizeCode(code),
      p_name: (name || "").trim(),
      p_email: normalizeEmail(email),
    },
    options
  );
}

/* -------------------------------------------------------------------------- *
 * Card shaping
 *
 * check_in() returns one entry per session in the term, stamped or not. The
 * card component wants a fixed-length strip so the empty slots keep their
 * positions, which is what makes "2 sessions to go" legible at a glance.
 * -------------------------------------------------------------------------- */

/** Slots drawn on a card. Eight sessions to a card, one card per term. */
export const CARD_SLOTS = 8;

/** "09.10" — the compact date printed under each stamp in the mockup. */
export function stampDate(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${mm}.${dd}`;
}

/**
 * Pad the term's sessions out to CARD_SLOTS so the strip is always the same
 * width. A term with only six sessions scheduled still draws eight circles,
 * because the card is a promise about the term rather than a report on what has
 * been scheduled so far.
 */
export function toStrip(card = []) {
  const bySlot = new Map(card.map((entry) => [entry.slot, entry]));
  return Array.from({ length: CARD_SLOTS }, (_, i) => {
    const slot = i + 1;
    const entry = bySlot.get(slot);
    return {
      slot,
      stamped: Boolean(entry?.stamped),
      label: entry ? stampDate(entry.starts_at) : "",
      title: entry?.title || "",
    };
  });
}

/** "2 sessions to go." / "Card full." — the line beside the strip. */
export function remainingLabel(card = []) {
  const stamped = card.filter((entry) => entry.stamped).length;
  const togo = Math.max(0, CARD_SLOTS - stamped);
  if (togo === 0) return "Card full.";
  return `${togo} session${togo === 1 ? "" : "s"} to go.`;
}
