import { initials, headshotAlt } from "../lib/board";
import { LinkedInIcon, MailIcon } from "./Icons";

const WIDTHS = [320, 480, 640, 960];
const SIZES =
  "(min-width: 1024px) 300px, (min-width: 640px) 45vw, 90vw";

/**
 * One board member.
 *
 * The role is the anchor of the card, not a caption under the name: it is set
 * larger, in Burnt Terracotta, above the name. Members are found by what they
 * do at least as often as by who they are.
 *
 * The photo slot is a fixed 1:1 box whether or not a photo exists, so adding
 * headshots later causes zero layout shift. Dropping a file at
 * public/board/<slug>.jpg and setting `photo: true` in board.js is the only
 * work required; derivatives are generated by scripts/build-headshots.mjs.
 *
 * `linkedin` and `email` are null for everyone until the values arrive
 * (revision 2 §6.4, §6.5). A missing link is omitted rather than rendered
 * dead, so the card degrades cleanly.
 */
const BoardCard = ({ member, eager = false, lead = false }) => {
  const { slug, name, role, detail, photo, linkedin, email } = member;

  return (
    <li
      className={`board-card list-none ${lead ? "board-card--lead sm:col-span-2" : ""}`}
    >
      <div
        className="board-photo overflow-hidden rounded-lg border border-rule bg-gray-light"
        style={{ aspectRatio: lead ? "16 / 10" : "1 / 1" }}
      >
        {photo ? (
          <picture>
            <source
              type="image/avif"
              sizes={SIZES}
              srcSet={WIDTHS.map((w) => `/board/${slug}-${w}.avif ${w}w`).join(", ")}
            />
            <source
              type="image/webp"
              sizes={SIZES}
              srcSet={WIDTHS.map((w) => `/board/${slug}-${w}.webp ${w}w`).join(", ")}
            />
            <img
              src={`/board/${slug}-640.jpg`}
              srcSet={WIDTHS.map((w) => `/board/${slug}-${w}.jpg ${w}w`).join(", ")}
              sizes={SIZES}
              alt={headshotAlt(member)}
              width="640"
              height="640"
              loading={eager ? "eager" : "lazy"}
              decoding="async"
              {...(eager ? { fetchpriority: "high" } : {})}
              className="h-full w-full object-cover"
            />
          </picture>
        ) : (
          <div
            aria-hidden="true"
            className="flex h-full w-full items-center justify-center"
          >
            <span
              className="font-display font-semibold text-coral-text"
              style={{
                fontSize: lead ? "var(--step-display)" : "var(--step-1)",
                letterSpacing: "0.01em",
              }}
            >
              {initials(name)}
            </span>
          </div>
        )}
      </div>

      <p
        className="board-role mt-4 font-display font-semibold text-coral-text"
        style={{
          fontSize: lead ? "var(--step-2)" : "var(--step-3)",
          maxWidth: "none",
        }}
      >
        {role}
      </p>

      <h3
        className="board-name sweep mt-1 inline font-display font-semibold text-ink"
        style={{ fontSize: "var(--step-small)" }}
      >
        {name}
      </h3>

      <p className="mt-2 text-meta text-gray-text">{detail}</p>

      {(linkedin || email) && (
        <ul className="mt-3 flex list-none flex-wrap gap-4 p-0">
          {linkedin && (
            <li>
              <a
                className="inline-flex items-center gap-1.5 text-meta text-ink no-underline sweep"
                href={linkedin}
                target="_blank"
                rel="noopener noreferrer"
              >
                <LinkedInIcon width={15} height={15} />
                <span>LinkedIn</span>
                <span className="sr-only"> profile for {name}</span>
              </a>
            </li>
          )}
          {email && (
            <li>
              <a
                className="inline-flex items-center gap-1.5 text-meta text-ink no-underline sweep"
                href={`mailto:${email}`}
              >
                <MailIcon width={15} height={15} />
                <span>Email</span>
                <span className="sr-only"> {name}</span>
              </a>
            </li>
          )}
        </ul>
      )}
    </li>
  );
};

export default BoardCard;
