/**
 * Write public/hacking-starts.ics from src/lib/event.js.
 *
 * SPEC §3.6 says the highlighted row's button links to an .ics file. Hand-
 * writing one would put the event's start time in a second place, and the
 * first schedule change would leave the countdown and the calendar file
 * disagreeing in a way nobody notices until someone shows up at the wrong
 * hour. Generated instead, from the same constants the page renders.
 *
 * Output is gitignored and regenerated by `npm run dev` and by `prebuild`.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { EVENT } from "../src/lib/event.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT = join(ROOT, "public", "hacking-starts.ics");

/** RFC 5545 UTC form: 20261107T020000Z. */
function toICSDate(iso) {
  const ms = Date.parse(iso);

  if (Number.isNaN(ms)) {
    throw new Error(`build-ics: "${iso}" is not a date Date.parse understands.`);
  }

  return new Date(ms).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
}

/**
 * RFC 5545 §3.1: lines are folded at 75 octets, continuation lines begin with
 * a single space. Calendar apps are mostly forgiving about this, and the one
 * that is not would drop the description.
 */
function fold(line) {
  if (line.length <= 75) return line;

  const parts = [line.slice(0, 75)];
  let rest = line.slice(75);

  while (rest.length > 74) {
    parts.push(` ${rest.slice(0, 74)}`);
    rest = rest.slice(74);
  }

  if (rest) parts.push(` ${rest}`);
  return parts.join("\r\n");
}

/** Commas, semicolons and backslashes are separators in a property value. */
const escape = (text) =>
  text.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,");

const lines = [
  "BEGIN:VCALENDAR",
  "VERSION:2.0",
  "PRODID:-//HACK1984//Website//EN",
  "CALSCALE:GREGORIAN",
  "METHOD:PUBLISH",
  "BEGIN:VEVENT",
  // Stable across rebuilds: re-importing the file updates the existing entry
  // instead of adding a second one to the invitee's calendar.
  "UID:hacking-starts@hack1984",
  // DTSTAMP must be the moment the file was written, not the event time.
  `DTSTAMP:${toICSDate(new Date().toISOString())}`,
  `DTSTART:${toICSDate(EVENT.hackingStartISO)}`,
  `DTEND:${toICSDate(EVENT.hackingEndISO)}`,
  `SUMMARY:${escape(`${EVENT.name} — hacking starts`)}`,
  `LOCATION:${escape(EVENT.venue)}`,
  `DESCRIPTION:${escape(EVENT.tagline)}`,
  "END:VEVENT",
  "END:VCALENDAR",
];

mkdirSync(dirname(OUT), { recursive: true });
// CRLF: RFC 5545 requires it, and Outlook enforces it.
writeFileSync(OUT, lines.map(fold).join("\r\n") + "\r\n", "utf8");

console.log(`[ics] ${EVENT.hackingStartISO} -> public/hacking-starts.ics`);
