/**
 * tokens.json -> src/styles/tokens.css
 *
 * The design system is delivered as tokens.json and that file stays the single
 * source of truth. Hand-copying its values into CSS would create a second one,
 * and the two would disagree the first time a colour moved. This script is the
 * only thing allowed to turn a token into a CSS custom property.
 *
 * Output is gitignored and regenerated by `npm run dev` and by `prebuild`.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT = join(ROOT, "src", "styles", "tokens.css");

/**
 * The theme to emit.
 *
 * tokens.json carries a "night" and a "day" value for every colour, but
 * SPEC §1 is headed "Night theme only; the site is dark" and nothing on the
 * page switches themes. Emitting an unreachable `[data-theme="day"]` block
 * would ship dead CSS that no one maintains and that quietly rots. The day
 * values stay in tokens.json, ready for the day the design asks for them.
 */
const THEME = "night";

/**
 * SPEC §1, "Extra values used on this page (not in tokens, add them as
 * page-level variables)".
 *
 * These are deliberately NOT written back into tokens.json: they belong to
 * this page, not to the HACK1984 system, and tokens.json is shared with the
 * poster and slide artwork.
 */
const PAGE_EXTRAS = {
  "chip-bg": ["#262626", "Gray label chips, track tag borders, header rule"],
  dash: ["#404040", "Dashed dividers: sponsor cells, countdown, schedule"],
  "ascii-bg": ["#120302", "Background of the ASCII image boxes"],
  "red-900": ["#3d0603", "Schedule time chip background"],
  "red-chip-text": ["#ff8a80", "Schedule time chip text"],
  "hero-gradient": [
    "linear-gradient(0deg, #1c0302 0%, #100201 35%, #050000 70%, #000000 100%)",
    "Hero background, rises from the bottom, hard stop at Sponsors",
  ],
  // The wordmark's red is NOT `accent`. Accent is the interface red — buttons,
  // the seconds digit, the one red pixel in an icon — and having the logo
  // share it made the mark read as another control. This is deeper and less
  // orange. It happens to equal tokens.json's Day-theme accent, but it is
  // written out rather than read from there: the two are not the same
  // decision and should not move together.
  "wordmark-accent": ["#d4190e", "The 1984 half of the wordmark"],
  "highlight-gradient": [
    "linear-gradient(90deg, #7a0d07 0%, #3d0603 45%, #0a0100 85%)",
    'The "Hacking starts" schedule row',
  ],
};

/**
 * The ASCII palette, dark to light (SPEC §1). Indexed rather than named: the
 * generator for ascii/*.html emits these as literal hex in per-run spans, so
 * these variables exist for anything else that needs to sit in the same ramp
 * (the track sponsor square, for one) and to document the ramp in one place.
 */
const ASCII_RAMP = [
  "#3a0a07",
  "#4a0c08",
  "#7e130c",
  "#c01d13",
  "#ff3b2f",
  "#ff7a70",
  "#ffd0ca",
];

const tokens = JSON.parse(readFileSync(join(ROOT, "tokens.json"), "utf8"));

const lines = [];
const push = (s = "") => lines.push(s);

push("/*");
push(" * GENERATED FILE — DO NOT EDIT.");
push(" *");
push(` * Written by scripts/build-tokens.mjs from tokens.json (v${tokens.version},`);
push(` * "${tokens.name}"), theme "${THEME}". Edit tokens.json and re-run`);
push(" * `npm run tokens`. This file is gitignored.");
push(" */");
push();
push(":root {");

push("  /* --- Colour (SPEC §1) ------------------------------------------- */");
for (const t of tokens.color.tokens) {
  push(`  /* ${t.usage} */`);
  push(`  --${t.name}: ${t.value[THEME]};`);
}

push();
push("  /* --- Page-level extras (SPEC §1) -------------------------------- */");
for (const [name, [value, usage]] of Object.entries(PAGE_EXTRAS)) {
  push(`  /* ${usage} */`);
  push(`  --${name}: ${value};`);
}

push();
push("  /* --- ASCII ramp, dark to light (SPEC §1) ------------------------ */");
ASCII_RAMP.forEach((hex, i) => push(`  --ascii-${i}: ${hex};`));

push();
push("  /* --- Type families (SPEC §1) ------------------------------------ */");
for (const [role, stack] of Object.entries(tokens.type.families)) {
  push(`  --font-${role}: ${stack};`);
}

push();
push(`  /* --- Spacing. ${tokens.spacing.note} ------------------------------------- */`);
for (const t of tokens.spacing.tokens) {
  push(`  --${t.name}: ${t.value}; /* ${t.usage} */`);
}

push();
push("  /* --- Radius. 0 everywhere; the pill is reserved and unused. ------ */");
for (const t of tokens.radius.tokens) {
  push(`  --${t.name}: ${t.value};`);
}

push();
push("  /* --- Rules and focus -------------------------------------------- */");
for (const t of tokens.rule.tokens) {
  push(`  --${t.name}: ${t.value}; /* ${t.usage} */`);
}

push("}");
push();

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"), "utf8");

const count =
  tokens.color.tokens.length +
  Object.keys(PAGE_EXTRAS).length +
  ASCII_RAMP.length +
  Object.keys(tokens.type.families).length +
  tokens.spacing.tokens.length +
  tokens.radius.tokens.length +
  tokens.rule.tokens.length;

console.log(`[tokens] ${count} variables -> src/styles/tokens.css`);
